# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  LT_USERNAME: $LT_USERNAME
  LT_ACCESS_KEY: $LT_ACCESS_KEY

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: configuration@1
  inputs:
    connection: 'Tunnel'
    isTunnelActivate: false

- script: |
    env:
        LT_BUILD_NAME: "custombuildname"
        LT_USERNAME: $LT_USERNAME
        LT_ACCESS_KEY: $LT_ACCESS_KEY
    npm install
    npm install -g protractor
    cd conf
    protractor single.conf.js
  displayName: 'npm install and build'

- task: Lambdatest.lambda-azure-pipeline-extention.showResults-task.LambdatestResults@1
  displayName: 'Lambdatest Results'

