# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  LT_USERNAME: "YOUR USERNAME HERE"
  LT_ACCESS_KEY: "YOUR ACCESS KEY HERE"

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: configuration@1
  inputs:
    connection: 'Tunnel'
    isTunnelActivate: true

- script: |
    npm install
    npm install -g protractor
    cd conf
    protractor single.conf.js
  displayName: 'npm install and build'

- task: stoptunnel@1